FROM python:3.14-slim

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Activate the project virtual environment by placing its binary directory at the front of the path.
# https://docs.astral.sh/uv/guides/integration/docker/#using-the-environment
ENV PATH="/.venv/bin:$PATH"

# Compile bytecode
# https://docs.astral.sh/uv/guides/integration/docker/#compiling-bytecode
ENV UV_COMPILE_BYTECODE=1

# uv Cache
# https://docs.astral.sh/uv/guides/integration/docker/#caching
ENV UV_LINK_MODE=copy

WORKDIR /app

# Install UV.
# https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
# https://hub.docker.com/r/astral/uv
COPY --from=docker.io/astral/uv:latest /uv /uvx /bin/

# Copy the project into the image.
COPY shared ./shared
COPY auth_api ./auth_api

WORKDIR /app/auth_api

ENV PYTHONPATH="/app:${PYTHONPATH}"

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# Sync the project
# Ref: https://docs.astral.sh/uv/guides/integration/docker/#installing-a-project
RUN uv sync --locked

# To debug through VSCode.
RUN uv add debugpy

EXPOSE 8000
EXPOSE 5678
CMD ["uv", "run", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
